baseURL = "https://wins-m.github.io/tickets/"
languageCode = "zh-cn"
title = "噗嗤！收藏集！"
theme = "tickets"
paginate = 60
enableRobotsTXT = true

[taxonomies]
  theater = "theaters"
  #rating = "ratings"

[params]
  description = "The ongoing movie ticket collection of Wins.M., started in 2018."
  images = ["images/tickets-social.jpg"]
  subTitle = "A Movie Ticket Collection"

[author]
  name = "Wins. M."
  homepage = "https://github.com/wins-m/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "All Tickets"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "theaters"
    name = "Theaters"
    pageRef = "/theaters/"
    weight = 3

