name: Deploy Hugo Site

on:
  push:
    paths:
      - 'content/**'      # 仅当content目录变化时触发
      - 'layouts/**'
      - 'config.toml'
  workflow_run:           # 当豆瓣监控工作流完成后触发
    workflows: ["Sync Douban to Hugo Content"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: yourusername/yourusername.github.io
          publish_dir: ./public

